### ISSUE TITLE
Compatibility with macOS 12.3

### ISSUE THREAD

**Issue by ChengS-U** [jessedobbelaere/alfred-iterm-profiles-workflow#11]
Hi, 

After macOS 12.3, Apple had been removed python2 by default. Have any possible that provide a python3 update? Thanks

**Comment by joelmellon** [comment]
For now you can reinstall 2.7. https://www.python.org/downloads/release/python-2718/

The install path changes from `/usr/bin/python` to `/usr/local/bin/python` so you'll need to update the workflow's `ItermProfileSearcher.py`; first line. You can also make a symlink if desired.

**Comment by jessedobbelaere** [comment]
Hi! This iterm-profiles-workflow depends on the package `alfred-workflow` which is not available yet for Python 3 🤨 I'm subscribed to https://github.com/deanishe/alfred-workflow/issues/97 in case there will be an update. Then we can provide a new version of this workflow, unless there's a better idea. Maybe a rewrite using https://github.com/sindresorhus/alfy ?

It's pretty bad that so many Alfred workflows still depend on Python 2 which has been EOL for a long time and removed in macOS 12.3...

**Comment by jessedobbelaere** [comment]
Please check https://github.com/jessedobbelaere/alfred-iterm-profiles-workflow/releases/tag/v2.0.0 for a release that supports Python 3 / macOS 12.3 😁

**Comment by joelmellon** [comment]
You're awesome @jessedobbelaere Thanks very much for this workflow. 🤘

**Comment by ChengS-U** [comment]
Thank you so much!!!
