### ISSUE TITLE
Unable to run task!

### ISSUE THREAD

**Issue by MaxHill** [jessedobbelaere/alfred-iterm-profiles-workflow#5]
I get this error for some reason

**Title:** 
Unable to run task!
**Body:** 
Reason: Couldn't posix_spawn: error 2

The external script may not exist, or doesn't have execute (+x) permissions.

**Comment by ericwen229** [comment]
@MaxHill Changing the first line of ItermProfileSearcher.py to `#!/usr/bin/python` works for me
